[project]
name = "scholar-stream"
version = "0.1.0"
description = "Scholar Stream Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.1.1",
    "ruff>=0.12.10",
    "snowflake>=1.7.0",
]
