USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS FIREHOSE_LOADER
    TYPE = SERVICE
    DEFAULT_ROLE = R_INGEST
    DEFAULT_NAMESPACE = SCHOLARSTREAM.RAW
    COMMENT = 'Service user for Kinesis Data Firehose to load into RAW';

USE ROLE SECURITYADMIN;

GRANT ROLE R_INGEST TO USER FIREHOSE_LOADER;
