USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_INGESTION
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_RESUME = TRUE
    AUTO_SUSPEND = 60
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Compute for ingestion';

CREATE WAREHOUSE IF NOT EXISTS WH_TRANSFORM
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_RESUME = TRUE
    AUTO_SUSPEND = 60
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Compute for creating/updating views';

CREATE WAREHOUSE IF NOT EXISTS WH_ANALYST
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_RESUME = TRUE
    AUTO_SUSPEND = 60
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Compute for app/analyst queries';

CREATE DATABASE IF NOT EXISTS SCHOLARSTREAM COMMENT = 'Demo project Firehose -> Snowflake';
CREATE SCHEMA IF NOT EXISTS SCHOLARSTREAM.RAW COMMENT = 'Landing (VARIANT JSON)';
CREATE SCHEMA IF NOT EXISTS SCHOLARSTREAM.CURATED COMMENT = 'Parsed views and metrics';
