USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS R_INGEST COMMENT = 'Ingestion: loading into RAW';
CREATE ROLE IF NOT EXISTS R_TRANSFORM COMMENT = 'Transform: creating views and reading RAW';
CREATE ROLE IF NOT EXISTS R_ANALYST COMMENT = 'Analysis: reading from CURATED';

GRANT ROLE R_INGEST TO ROLE SYSADMIN;
GRANT ROLE R_TRANSFORM TO ROLE SYSADMIN;
GRANT ROLE R_ANALYST TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE WH_INGESTION TO ROLE R_INGEST;
GRANT USAGE ON WAREHOUSE WH_TRANSFORM TO ROLE R_TRANSFORM;
GRANT USAGE ON WAREHOUSE WH_ANALYST TO ROLE R_ANALYST;

GRANT USAGE ON DATABASE SCHOLARSTREAM TO ROLE R_INGEST;
GRANT USAGE ON DATABASE SCHOLARSTREAM TO ROLE R_TRANSFORM;
GRANT USAGE ON DATABASE SCHOLARSTREAM TO ROLE R_ANALYST;

GRANT USAGE ON SCHEMA SCHOLARSTREAM.RAW TO ROLE R_INGEST;
GRANT USAGE ON SCHEMA SCHOLARSTREAM.RAW TO ROLE R_TRANSFORM;

GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA SCHOLARSTREAM.RAW TO ROLE R_INGEST;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA SCHOLARSTREAM.RAW TO ROLE R_INGEST;

GRANT SELECT ON ALL TABLES IN SCHEMA SCHOLARSTREAM.RAW TO ROLE R_TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCHOLARSTREAM.RAW TO ROLE R_TRANSFORM;

GRANT USAGE ON SCHEMA SCHOLARSTREAM.CURATED TO ROLE R_TRANSFORM;
GRANT USAGE ON SCHEMA SCHOLARSTREAM.CURATED TO ROLE R_ANALYST;

GRANT CREATE VIEW ON SCHEMA SCHOLARSTREAM.CURATED TO ROLE R_TRANSFORM;

GRANT SELECT ON ALL VIEWS IN SCHEMA SCHOLARSTREAM.CURATED TO ROLE R_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SCHOLARSTREAM.CURATED TO ROLE R_ANALYST;
