USE ROLE SYSADMIN;
USE DATABASE SCHOLARSTREAM;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS OPENALEX_EVENTS (
    RECORD VARIANT,
    RECORD_METADATA VARIANT,
    EVENT_TS TIMESTAMP_NTZ,
    INGEST_TS TIMESTAMP_NTZ,
    LANDED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE STRING DEFAULT 'openalex',
    _LOAD_ID STRING
);

COMMENT ON TABLE OPENALEX_EVENTS IS 'Landing table for OpenAlex events (JSON in VARIANT + metadata)';
