USE ROLE SYSADMIN;
USE DATABASE SCHOLARSTREAM;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE OPENALEX_EVENTS (
    RECORD VARIANT,
    RECORD_METADATA VARIANT
);

COMMENT ON TABLE OPENALEX_EVENTS IS 'Landing table for OpenAlex events (JSON in VARIANT + metadata)';
