USE ROLE SECURITYADMIN;

GRANT CREATE MASKING POLICY ON SCHEMA SCHOLARSTREAM.CURATED TO ROLE R_TRANSFORM;
GRANT APPLY  MASKING POLICY ON ACCOUNT TO ROLE R_TRANSFORM;

USE ROLE R_TRANSFORM;
USE DATABASE SCHOLARSTREAM;
USE SCHEMA CURATED;

CREATE OR REPLACE MASKING POLICY MP_EMAIL_MASK AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('R_TRANSFORM','SYSADMIN') THEN val
        ELSE '***MASKED***'
    END;

ALTER VIEW VW_WORKS
    MODIFY COLUMN email SET MASKING POLICY MP_EMAIL_MASK;