USE ROLE SECURITYADMIN;

GRANT CREATE MASKING POLICY ON SCHEMA SCHOLARSTREAM.CURATED TO ROLE R_TRANSFORM;
GRANT APPLY  MASKING POLICY ON ACCOUNT TO ROLE R_TRANSFORM;

USE ROLE R_TRANSFORM;
USE DATABASE SCHOLARSTREAM;
USE SCHEMA CURATED;

CREATE OR REPLACE MASKING POLICY MP_MASK_EMAIL AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'R_TRANSFORM', 'R_INGEST') THEN val
        WHEN val IS NULL THEN NULL
        WHEN POSITION('@', val) = 0 THEN '***'
        ELSE CONCAT(LEFT(val, 1), '***', SUBSTR(val, POSITION('@', val)))
    END;

ALTER VIEW VW_WORKS MODIFY COLUMN EMAIL UNSET MASKING POLICY;
ALTER VIEW VW_WORKS MODIFY COLUMN EMAIL SET MASKING POLICY MP_MASK_EMAIL;

COMMENT ON MASKING POLICY MP_MASK_EMAIL IS 'Masks emails for non-admin/engineering roles; applied on CURATED.VW_WORKS.EMAIL';