name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    name: Lint, SQL dry-run, Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            requirements-ci.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Ruff check
        run: ruff check .

      - name: Validate SQL order (dry-run)
        env:
          PYTHONPATH: .
        run: python sql/apply.py --dry-run

      - name: Pytest (with coverage)
        env:
          PYTHONPATH: .
        run: pytest -q --cov=ingestion --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
